package opencep.plan;

public enum TreePlanBuilderTypes {
  TRIVIAL_LEFT_DEEP_TREE,
  SORT_BY_FREQUENCY_LEFT_DEEP_TREE,
  GREEDY_LEFT_DEEP_TREE,
  LOCAL_SEARCH_LEFT_DEEP_TREE,
  DYNAMIC_PROGRAMMING_LEFT_DEEP_TREE,
  DYNAMIC_PROGRAMMING_BUSHY_TREE,
  ZSTREAM_BUSHY_TREE,
  ORDERED_ZSTREAM_BUSHY_TREE,
  INVARIANT_AWARE_GREEDY_LEFT_DEEP_TREE,
  INVARIANT_AWARE_ZSTREAM_BUSHY_TREE
}
